"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock, Loader2 } from "lucide-react";

const services = [{ name: "Website Development", description: "A high-performing website built around your business." }, { name: "Web Application", description: "Scalable web products for real operational needs." }, { name: "Mobile App", description: "Thoughtful mobile experiences for iOS and Android." }, { name: "AI Solution", description: "Practical AI automation and intelligent workflows." }, { name: "UI/UX Design", description: "Clear product experiences your customers enjoy using." }, { name: "Custom Project", description: "Let’s explore the right solution for your idea." }];
const weekdays = ["S", "M", "T", "W", "T", "F", "S"];
const input = "h-11 w-full rounded-lg border border-white/10 bg-[#050816] px-3 text-sm text-white outline-none transition placeholder:text-white/38 focus:border-[#35b7ff] focus:ring-2 focus:ring-[#35b7ff]/20";
const key = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;

export function ConsultationBooking() {
  const [step, setStep] = useState(1), [service, setService] = useState(""), [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)), [availableDates, setAvailableDates] = useState<string[]>([]), [date, setDate] = useState(""), [slots, setSlots] = useState<string[]>([]), [time, setTime] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState(""), [complete, setComplete] = useState(false);
  useEffect(() => { fetch("/api/appointments/availability").then(r => r.json()).then(body => setAvailableDates(Array.isArray(body.dates) ? body.dates : [])).catch(() => setError("Availability could not be loaded. Please try again.")); }, []);
  useEffect(() => { if (!date) return; setTime(""); fetch(`/api/appointments/availability?date=${date}`).then(r => r.json()).then(body => { setSlots(Array.isArray(body.slots) ? body.slots : []); if (body.error) setError(body.error); }).catch(() => setError("Time slots could not be loaded.")); }, [date]);
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1), count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(first.getDay()).fill(null), ...Array.from({ length: count }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))]; }, [month]);
  const formattedDate = date ? new Date(`${date}T12:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) : "";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!service || !date || !time) return; setSaving(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email: data.get("email"), phone: data.get("phone"), company: data.get("company"), projectType: service, projectDescription: data.get("projectDescription"), appointmentDate: date, appointmentTime: time }) }); const body = await response.json().catch(() => null); setSaving(false); if (!response.ok) { setError(body?.error || "Your booking could not be submitted."); if (/just booked/i.test(body?.error || "")) { setDate(""); setTime(""); } return; } setComplete(true); setStep(4); }
  if (complete) return <section className="mx-auto max-w-2xl rounded-2xl border border-white/10 bg-card p-6 text-center shadow-soft-lg sm:p-10"><CheckCircle2 className="mx-auto h-14 w-14 text-[#35b7ff]" /><p className="mt-5 text-sm font-semibold uppercase tracking-[.18em] text-[#35b7ff]">Consultation requested</p><h1 className="mt-3 text-3xl font-black">We&apos;ve received your request.</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-muted-foreground">We&apos;ll confirm your selected time and contact you by email.</p><div className="mx-auto mt-7 grid max-w-md gap-3 rounded-xl border border-white/10 bg-white/[.03] p-5 text-left text-sm"><p><b>{service}</b></p><p>{formattedDate}</p><p>{time} · 30 minutes</p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href="/" className="inline-flex h-11 items-center justify-center rounded-lg bg-gradient-to-r from-[#8c1cff] to-[#19a8ff] px-5 text-sm font-bold text-white">Back to KenoraTech</Link><button onClick={() => { setComplete(false); setStep(1); setDate(""); setTime(""); setService(""); }} className="h-11 rounded-lg border border-white/15 px-5 text-sm font-bold">Book another consultation</button></div></section>;
  return <div className="mx-auto max-w-6xl"><div className="mb-8 grid grid-cols-4 gap-2 text-center text-xs font-bold sm:text-sm">{["Consultation", "Date & Time", "Your Details", "Confirmation"].map((label, index) => <div key={label} className={index + 1 <= step ? "text-[#35b7ff]" : "text-muted-foreground"}><span className={index + 1 <= step ? "mx-auto mb-2 grid h-7 w-7 place-items-center rounded-full bg-[#35b7ff] text-[#050816]" : "mx-auto mb-2 grid h-7 w-7 place-items-center rounded-full border border-white/15"}>{index + 1}</span>{label}</div>)}</div>
    {error ? <p className="mb-5 rounded-lg border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200" role="alert">{error}</p> : null}
    {step === 1 ? <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(item => <button type="button" key={item.name} onClick={() => { setService(item.name); setStep(2); setError(""); }} className={`rounded-xl border p-5 text-left transition ${service === item.name ? "border-[#35b7ff] bg-[#35b7ff]/10 ring-1 ring-[#35b7ff]/35" : "border-white/10 bg-card hover:border-white/25"}`}><h2 className="font-bold">{item.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-muted-foreground">{item.description}</p><p className="mt-4 flex items-center gap-2 text-xs font-bold text-[#35b7ff]"><Clock className="h-4 w-4" />30 minutes</p></button>)}</section> : null}
    {step === 2 ? <section className="grid gap-6 lg:grid-cols-[1fr_.82fr]"><div className="rounded-xl border border-white/10 bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><button type="button" aria-label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="grid h-11 w-11 place-items-center rounded-lg border border-white/10"><ChevronLeft className="h-5 w-5" /></button><h2 className="font-bold">{month.toLocaleDateString("en-IN", { month: "long", year: "numeric" })}</h2><button type="button" aria-label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="grid h-11 w-11 place-items-center rounded-lg border border-white/10"><ChevronRight className="h-5 w-5" /></button></div><div className="mt-6 grid grid-cols-7 gap-1 text-center text-xs">{weekdays.map((label, index) => <span key={`${label}-${index}`} className="py-2 text-muted-foreground">{label}</span>)}{days.map((day, index) => !day ? <span key={`blank-${index}`} /> : <button key={key(day)} type="button" disabled={!availableDates.includes(key(day))} onClick={() => setDate(key(day))} className={`mx-auto grid h-10 w-10 place-items-center rounded-lg transition ${date === key(day) ? "bg-[#35b7ff] font-bold text-[#050816]" : availableDates.includes(key(day)) ? "border border-[#35b7ff]/35 text-white hover:bg-[#35b7ff]/15" : "cursor-not-allowed text-white/25"}`}>{day.getDate()}</button>)}</div></div><aside className="rounded-xl border border-white/10 bg-card p-5 sm:p-6"><p className="text-sm text-muted-foreground">{date ? `Available times for ${formattedDate}` : "Select an available date to see times."}</p>{date ? <div className="mt-5 grid grid-cols-2 gap-3">{slots.map(slot => <button type="button" onClick={() => setTime(slot)} key={slot} className={`min-h-11 rounded-lg border px-3 text-sm font-bold transition ${time === slot ? "border-[#35b7ff] bg-[#35b7ff]/15 text-[#8edcff]" : "border-white/10 hover:border-white/25"}`}>{slot}</button>)}{!slots.length ? <p className="col-span-2 text-sm text-muted-foreground">No slots remain for this date.</p> : null}</div> : null}<div className="mt-8 flex justify-between"><button type="button" onClick={() => setStep(1)} className="text-sm font-bold text-muted-foreground">← Change consultation</button><button type="button" disabled={!date || !time} onClick={() => setStep(3)} className="h-11 rounded-lg bg-gradient-to-r from-[#8c1cff] to-[#19a8ff] px-5 text-sm font-bold text-white disabled:opacity-40">Continue</button></div></aside></section> : null}
    {step === 3 ? <section className="grid gap-6 lg:grid-cols-[1fr_.7fr]"><form onSubmit={submit} className="rounded-xl border border-white/10 bg-card p-5 sm:p-6"><h2 className="text-xl font-black">Your details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Full name<input required name="name" autoComplete="name" className={input} /></label><label className="grid gap-2 text-sm font-medium">Email address<input required type="email" name="email" autoComplete="email" className={input} /></label><label className="grid gap-2 text-sm font-medium">Phone number<input required type="tel" name="phone" autoComplete="tel" className={input} /></label><label className="grid gap-2 text-sm font-medium">Company <span className="font-normal text-muted-foreground">(optional)</span><input name="company" autoComplete="organization" className={input} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Project type<input readOnly value={service} className={`${input} text-white/60`} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Project description<textarea required name="projectDescription" rows={5} className="w-full rounded-lg border border-white/10 bg-[#050816] p-3 text-sm text-white outline-none focus:border-[#35b7ff]" placeholder="Tell us what you&apos;d like to discuss." /></label></div><div className="mt-6 flex items-center justify-between gap-3"><button type="button" onClick={() => setStep(2)} className="text-sm font-bold text-muted-foreground">← Change date or time</button><button disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-lg bg-gradient-to-r from-[#8c1cff] to-[#19a8ff] px-5 text-sm font-bold text-white disabled:opacity-60">{saving ? <><Loader2 className="h-4 w-4 animate-spin" />Requesting...</> : "Request Consultation"}</button></div></form><aside className="h-fit rounded-xl border border-white/10 bg-card p-5"><CalendarDays className="h-5 w-5 text-[#35b7ff]" /><h2 className="mt-4 font-black">Consultation</h2><dl className="mt-4 grid gap-4 text-sm"><div><dt className="text-muted-foreground">Type</dt><dd className="mt-1 font-semibold">{service}</dd></div><div><dt className="text-muted-foreground">Date</dt><dd className="mt-1 font-semibold">{formattedDate}</dd></div><div><dt className="text-muted-foreground">Time</dt><dd className="mt-1 font-semibold">{time}</dd></div><div><dt className="text-muted-foreground">Duration</dt><dd className="mt-1 font-semibold">30 minutes</dd></div></dl></aside></section> : null}
  </div>;
}
