"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { BookOpen, CalendarDays, ChevronRight, Clock3, Mail, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

export type LegalSection = { title: string; body: string[]; bullets?: string[] };
type LegalPageProps = { title: string; description: string; updatedAt: string; sections: LegalSection[]; version?: string };
const slugify = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const infoItems: { icon: typeof BookOpen; label: string; value: (version: string, updatedAt: string, sectionCount: number) => string }[] = [
  { icon: BookOpen, label: "Version", value: (version) => version },
  { icon: CalendarDays, label: "Effective date", value: (_, updatedAt) => updatedAt },
  { icon: Clock3, label: "Last updated", value: (_, updatedAt) => updatedAt },
  { icon: Clock3, label: "Reading time", value: (_, __, sectionCount) => `${Math.max(3, Math.ceil(sectionCount * 0.7))} min` }
];

export function LegalPage({ title, description, updatedAt, sections, version = "1.0" }: LegalPageProps) {
  const [active, setActive] = useState(slugify(sections[0]?.title || ""));
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); }), { rootMargin: "-28% 0px -62%" }); document.querySelectorAll("[data-legal-section]").forEach(item => observer.observe(item)); return () => observer.disconnect(); }, []);
  return <div className="relative overflow-hidden bg-[#030711] text-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_9%,rgba(143,59,255,.2),transparent_22rem),radial-gradient(circle_at_86%_19%,rgba(21,168,255,.16),transparent_24rem),linear-gradient(180deg,#050816,#030711)]" /><div className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(111,99,255,.18)_1px,transparent_1px),linear-gradient(90deg,rgba(47,165,255,.12)_1px,transparent_1px)] [background-size:74px_74px]" />
    <section className="container relative grid gap-10 py-20 lg:grid-cols-[1fr_.75fr] lg:py-28"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><span className="inline-flex items-center gap-2 rounded-full border border-[#a970ff]/55 bg-[#3c176a]/30 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#d9b9ff]"><ShieldCheck className="h-4 w-4" /> Legal center</span><h1 className="mt-6 text-5xl font-black sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/68">{description}</p></motion.div><motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .1 }} className="relative mx-auto flex h-52 w-full max-w-md items-center justify-center overflow-hidden rounded-[2rem] border border-[#7654d6]/55 bg-[#0c1431]/65 shadow-[0_0_46px_rgba(77,84,255,.25)] backdrop-blur-xl"><div className="absolute h-40 w-40 rounded-full border border-[#9250ff]/45 shadow-[0_0_45px_rgba(126,55,255,.45)]"/><BookOpen className="relative h-20 w-20 text-[#72d8ff] drop-shadow-[0_0_20px_rgba(57,184,255,.75)]" /></motion.div></section>
    <section className="container relative pb-20"><div className="grid gap-6 rounded-2xl border border-white/[.1] bg-[#0a1127]/76 p-6 shadow-[0_0_40px_rgba(65,69,255,.13)] backdrop-blur-xl sm:grid-cols-4">{infoItems.map(({ icon: Icon, label, value }) => <div key={label} className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#5424a7]/32 text-[#b075ff]"><Icon className="h-5 w-5" /></div><div><p className="text-xs text-white/47">{label}</p><p className="mt-1 text-sm font-bold">{value(version, updatedAt, sections.length)}</p></div></div>)}</div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[270px_minmax(0,1fr)]"><aside className="lg:sticky lg:top-28 lg:self-start"><nav className="rounded-2xl border border-white/[.1] bg-[#091126]/78 p-4 backdrop-blur-xl" aria-label={`${title} sections`}><p className="px-3 pb-3 text-xs font-bold uppercase tracking-[.16em] text-[#a979ff]">On this page</p><div className="max-h-[58vh] space-y-1 overflow-y-auto">{sections.map(section => { const id = slugify(section.title); return <a key={id} href={`#${id}`} className={`flex items-center justify-between rounded-xl px-3 py-2.5 text-sm transition ${active === id ? "bg-[#7736e8]/20 text-white" : "text-white/57 hover:bg-white/[.05] hover:text-white"}`}><span>{section.title}</span>{active === id && <ChevronRight className="h-4 w-4 text-[#69dbff]" />}</a>; })}</div></nav></aside><div className="space-y-5">{sections.map((section,index) => <motion.article key={section.title} id={slugify(section.title)} data-legal-section initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: Math.min(index*.03,.18) }} className="scroll-mt-28 rounded-2xl border border-white/[.1] bg-[#091126]/76 p-6 shadow-[inset_0_1px_0_rgba(255,255,255,.05)] backdrop-blur-xl sm:p-8"><div className="flex gap-4"><div className="flex h-11 w-11 flex-none items-center justify-center rounded-xl bg-gradient-to-br from-[#7c2de8] to-[#1c98e8] text-white shadow-[0_0_22px_rgba(91,67,255,.28)]"><span className="font-black">{String(index + 1).padStart(2,"0")}</span></div><div className="min-w-0"><h2 className="text-2xl font-black">{section.title}</h2><div className="mt-3 h-px w-14 bg-gradient-to-r from-[#b045ff] to-[#33c6ff]" /></div></div><div className="mt-6 space-y-4 text-sm leading-7 text-white/67 sm:text-base">{section.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.bullets?.length ? <ul className="space-y-2 pt-1">{section.bullets.map(item => <li key={item} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 flex-none rounded-full bg-[#6fdcff] shadow-[0_0_8px_#6fdcff]" />{item}</li>)}</ul> : null}</div></motion.article>)}</div></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-[#5a55bd]/45 bg-[#101738]/75 p-7"><h2 className="text-2xl font-black">Still Have Questions?</h2><p className="mt-3 max-w-xl leading-7 text-white/65">Our team is happy to help with any questions about these policies or how we handle your information.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="inline-flex h-11 items-center justify-center rounded-xl bg-gradient-to-r from-[#8e2aff] to-[#149dff] px-5 text-sm font-bold">Contact Us</Link><a href="mailto:hello@kenoratech.com" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-white/20 px-5 text-sm font-bold"><Mail className="h-4 w-4 text-[#6edfff]"/>Email Support</a></div></div><address className="not-italic rounded-2xl border border-white/[.1] bg-[#091126]/76 p-7 text-sm leading-7 text-white/64"><h2 className="text-lg font-black text-white">Contact information</h2><p className="mt-3">Support: hello@kenoratech.com<br/>Legal: legal@kenoratech.com<br/>Business: business@kenoratech.com<br/>+91 73835 30982<br/>Valsad, Gujarat, India</p></address></div>
    </section></div>;
}
