import { ObjectId, type Document } from "mongodb";
import { getMongoDb } from "@/lib/mongodb";

export type Application = { id: string; jobTitle: string; fullName: string; email: string; phone?: string; location?: string; profileUrl?: string; coverLetter?: string; resumeName?: string; resumeUrl?: string; status: "New" | "Shortlisted" | "Rejected" | "Interview" | "Hired"; createdAt: string };
const clean = (value: unknown) => typeof value === "string" ? value.trim() : "";
function normalize(doc: Document): Application { return { id: doc._id.toString(), jobTitle: doc.jobTitle, fullName: doc.fullName, email: doc.email, phone: doc.phone || undefined, location: doc.location || undefined, profileUrl: doc.profileUrl || undefined, coverLetter: doc.coverLetter || undefined, resumeName: doc.resumeName || undefined, resumeUrl: doc.resumeUrl || undefined, status: doc.status || "New", createdAt: doc.createdAt?.toISOString?.() || new Date().toISOString() }; }
export async function createApplication(input: Record<string, unknown>) { const jobTitle = clean(input.jobTitle), fullName = clean(input.fullName), email = clean(input.email); if (!jobTitle || !fullName || !email) throw new Error("Job title, full name and email are required."); const db = await getMongoDb(); const result = await db.collection("applications").insertOne({ jobTitle, fullName, email, phone: clean(input.phone), location: clean(input.location), profileUrl: clean(input.profileUrl), coverLetter: clean(input.coverLetter), resumeName: clean(input.resumeName), resumeUrl: clean(input.resumeUrl), status: "New", createdAt: new Date(), updatedAt: new Date() }); const doc = await db.collection("applications").findOne({ _id: result.insertedId }); if (!doc) throw new Error("Application could not be loaded."); return normalize(doc); }
export async function listApplications() { return (await (await getMongoDb()).collection("applications").find({}).sort({ createdAt: -1 }).toArray()).map(normalize); }
export async function updateApplicationStatus(id: string, status: Application["status"]) { if (!ObjectId.isValid(id) || !["New", "Shortlisted", "Rejected", "Interview", "Hired"].includes(status)) throw new Error("Invalid application update."); const collection = (await getMongoDb()).collection("applications"); await collection.updateOne({ _id: new ObjectId(id) }, { $set: { status, updatedAt: new Date() } }); const doc = await collection.findOne({ _id: new ObjectId(id) }); if (!doc) throw new Error("Application could not be found."); return normalize(doc); }
