"use client";

import { FormEvent, useEffect, useState } from "react";
import { BriefcaseBusiness, Edit3, Plus, Trash2, X } from "lucide-react";
import type { Job, JobInput } from "@/lib/jobs";
import { PageHeader } from "@/components/admin/PageHeader";
import { EmptyState } from "@/components/admin/EmptyState";
import { Loading } from "@/components/admin/Loading";

const blank: JobInput = { title: "", department: "Engineering", location: "Remote", type: "Full-time", experience: "", salary: "", skills: [], description: "", published: true };

export function JobsManager() {
  const [jobs, setJobs] = useState<Job[]>([]), [loading, setLoading] = useState(true), [editing, setEditing] = useState<Job | null>(null), [creating, setCreating] = useState(false), [status, setStatus] = useState("");
  async function load() { const token = localStorage.getItem("kenora-admin-token") || ""; const r = await fetch("/api/jobs", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const b = await r.json().catch(() => null); setJobs(r.ok ? b?.jobs || [] : []); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function remove(id: string) { if (!confirm("Delete this job opening?")) return; const token = localStorage.getItem("kenora-admin-token") || ""; const r = await fetch(`/api/jobs/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); setStatus(r.ok ? "Job deleted." : "Job could not be deleted."); if (r.ok) void load(); }
  if (loading) return <Loading />;
  return <div className="grid gap-7"><PageHeader title="Careers & Open Positions" description="Create, publish, edit and remove jobs shown on the Careers page." action={<button onClick={() => setCreating(true)} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-gradient-to-r from-[#8B5CF6] to-[#3B82F6] px-4 text-sm font-bold"><Plus className="h-4 w-4" /> Add job</button>} />{status && <p className="rounded-2xl border border-white/[0.08] bg-[#0D1323]/78 px-4 py-3 text-sm text-white/70">{status}</p>}{jobs.length ? <div className="grid gap-3">{jobs.map(job => <article key={job.id} className="flex flex-col gap-4 rounded-2xl border border-white/[0.08] bg-[#0D1323]/78 p-5 md:flex-row md:items-center"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#8B5CF6]/16 text-[#a991ff]"><BriefcaseBusiness className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-white">{job.title}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${job.published ? "bg-emerald-400/12 text-emerald-300" : "bg-amber-400/12 text-amber-200"}`}>{job.published ? "Published" : "Draft"}</span></div><p className="mt-1 text-sm text-white/52">{job.department} · {job.location} · {job.type} · {job.experience}</p></div><div className="flex gap-2"><button onClick={() => setEditing(job)} className="flex h-10 items-center gap-2 rounded-xl border border-white/[0.08] px-3 text-sm text-white/72"><Edit3 className="h-4 w-4" /> Edit</button><button onClick={() => void remove(job.id)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/[0.08] text-red-200"><Trash2 className="h-4 w-4" /></button></div></article>)}</div> : <EmptyState title="No open positions" description="Add your first opening to publish it on the Careers page." />}{(creating || editing) && <JobModal job={editing} onClose={() => { setCreating(false); setEditing(null); }} onSaved={() => { setCreating(false); setEditing(null); setStatus("Job saved."); void load(); }} />}</div>;
}

function JobModal({ job, onClose, onSaved }: { job: Job | null; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<JobInput>(job ? { title: job.title, department: job.department, location: job.location, type: job.type, experience: job.experience, salary: job.salary, skills: job.skills, description: job.description, published: job.published } : blank); const [error, setError] = useState("");
  const change = (key: keyof JobInput, value: string | boolean) => setForm(current => ({ ...current, [key]: key === "skills" ? String(value).split(",").map(x => x.trim()).filter(Boolean) : value }));
  async function save(e: FormEvent) { e.preventDefault(); const token = localStorage.getItem("kenora-admin-token") || ""; const r = await fetch(job ? `/api/jobs/${job.id}` : "/api/jobs", { method: job ? "PUT" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(form) }); if (r.ok) onSaved(); else { const b = await r.json().catch(() => null); setError(b?.error || "Unable to save job."); } }
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-[#02040d]/82 p-4 backdrop-blur"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-[#8B5CF6]/35 bg-[#0D1323] p-6 shadow-2xl"><div className="flex items-start justify-between gap-5"><div><h2 className="text-xl font-black">{job ? "Edit position" : "Create position"}</h2><p className="mt-1 text-sm text-white/55">Published roles appear on the Careers page.</p></div><button type="button" onClick={onClose}><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([['title','Job title'],['department','Department'],['location','Location'],['type','Employment type'],['experience','Experience'],['salary','Salary range']] as const).map(([key,label]) => <Field key={key} label={label} value={String(form[key])} onChange={value => change(key, value)} />)}</div><div className="mt-4"><Field label="Skills (comma separated)" value={form.skills.join(", ")} onChange={value => change("skills", value)} /></div><label className="mt-4 grid gap-2 text-sm font-semibold">Description<textarea required value={form.description} onChange={e => change("description", e.target.value)} rows={4} className="rounded-xl border border-white/[0.1] bg-[#050816] p-3 text-sm font-normal outline-none" /></label><label className="mt-4 flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={form.published} onChange={e => change("published", e.target.checked)} className="accent-[#8B5CF6]" /> Publish this position</label>{error && <p className="mt-4 text-sm text-red-200">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm text-white/60">Cancel</button><button className="rounded-xl bg-gradient-to-r from-[#8B5CF6] to-[#3B82F6] px-5 py-2.5 text-sm font-bold">Save position</button></div></form></div>;
}

const selectOptions: Record<string, string[]> = {
  "Job title": ["AI Engineer", "Android Developer", "Angular Developer", "ASP.NET Developer", "Backend Developer", "Business Analyst", "Business Development Executive", "Cloud Engineer", "Content Writer", "Cybersecurity Engineer", "Data Analyst", "Data Engineer", "Data Scientist", "DevOps Engineer", "Digital Marketing Executive", "Flutter Developer", "Frontend Developer", "Full Stack Developer", "Game Developer", "Graphic Designer", "HR Executive", "iOS Developer", "Java Developer", "Java Spring Boot Developer", "Laravel Developer", "Machine Learning Engineer", "Manual QA Tester", "MERN Stack Developer", "Mobile App Developer", "Next.js Developer", "Node.js Developer", "PHP Developer", "Product Manager", "Project Manager", "Prompt Engineer", "Python Developer", "QA Engineer", "React Developer", "React Native Developer", "Ruby on Rails Developer", "Sales Executive", "SEO Specialist", "Site Reliability Engineer", "Software Development Intern", "Software Engineer", "Technical Support Engineer", "UI Designer", "UI/UX Designer", "UX Researcher", "Vue.js Developer", "Web Designer", "WordPress Developer"],
  Location: ["Remote", "Onsite"],
  Department: ["Engineering", "Frontend", "Backend", "Full Stack", "Mobile Development", "UI/UX Design", "Graphic Design", "Quality Assurance", "DevOps", "Cloud", "Cybersecurity", "Artificial Intelligence", "Data Science", "Product", "Project Management", "Marketing", "SEO", "Content", "Sales", "Business Development", "Customer Support", "Human Resources", "Finance", "Administration", "Internships"],
  "Employment type": ["Full-time", "Part-time", "Internship", "Contract", "Freelance", "Temporary"],
  Experience: ["Fresher", "0-1 Years", "1-2 Years", "2-3 Years", "3-5 Years", "5-7 Years", "7-10 Years", "10+ Years"],
  Skills: ["HTML", "CSS", "JavaScript", "TypeScript", "React", "Next.js", "Vue", "Angular", "Node.js", "Express", "MongoDB", "MySQL", "PostgreSQL", "AWS", "Azure", "Docker", "Git", "GitHub", "Tailwind CSS", "Figma", "Python", "Laravel", "OpenAI API"]
};

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  const [dragging, setDragging] = useState(false);
  if (label === "Department") return null;
  const options = label.startsWith("Skills") ? selectOptions.Skills : selectOptions[label];
  const selected = value.split(",").map((item) => item.trim()).filter(Boolean);
  const toggle = (option: string) => onChange((selected.includes(option) ? selected.filter((item) => item !== option) : [...selected, option]).join(", "));
  if (label.startsWith("Skills")) return <div className="grid gap-2 text-sm font-semibold" onPointerUp={() => setDragging(false)} onPointerLeave={() => setDragging(false)}><div className="flex items-center justify-between"><span>{label}</span><span className="text-xs font-normal text-white/45">Click or drag across skills</span></div><div className="flex max-h-44 flex-wrap gap-2 overflow-y-auto rounded-xl border border-white/[0.1] bg-[#050816] p-3">{selectOptions.Skills.map(option => <button type="button" key={option} onPointerDown={() => { setDragging(true); toggle(option); }} onPointerEnter={() => { if (dragging && !selected.includes(option)) toggle(option); }} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold transition ${selected.includes(option) ? "border-[#8B5CF6]/70 bg-[#8B5CF6]/25 text-white" : "border-white/[0.1] bg-white/[0.03] text-white/62 hover:border-[#3B82F6]/60"}`}>{option}</button>)}</div>{selected.length ? <p className="text-xs font-normal text-white/45">Selected: {selected.join(", ")}</p> : null}</div>;
  if (options) return <label className="grid gap-2 text-sm font-semibold">{label}<select required value={value} onChange={event => onChange(event.target.value)} className="h-11 rounded-xl border border-white/[0.1] bg-[#050816] px-3 text-sm font-normal outline-none"><option value="" disabled>Select {label.toLowerCase()}</option>{options.map(option => <option key={option}>{option}</option>)}</select></label>;
  return <label className="grid gap-2 text-sm font-semibold">{label}<input required={label !== "Salary range"} value={value} onChange={e => onChange(e.target.value)} className="h-11 rounded-xl border border-white/[0.1] bg-[#050816] px-3 text-sm font-normal outline-none" /></label>;
}
